workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    scripts:
      - name: Install Node Dependencies
        script: |
          npm install --legacy-peer-deps  # Bypass peer dependency conflict
      - name: Build Android Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
